version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_webapp
    ports:
      - "${PORT}:3000"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev"
    networks:
      - default

volumes:
  node_modules: